/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Users {
  email: string;
  id: Generated<string>;
  name: string | null;
  password: string | null;
}

export interface Objectives {
  id: Generated<string>;
  title: string;
  description: string;
  notifyAt: string;
  createdAt: Date | null;
  updatedAt: Date;
  isCompleted: boolean;
}

export interface UserObjectiveShares {
  id: Generated<string>;
  userful: string;
  objectheld: string;
}

export interface DB {
  users: Users;
  objectives: Objectives;
  user_objective_shares: UserObjectiveShares;
}
